version: "3.8"

services:
  flask-app:
    build: .
    image: flask-app
    container_name: flask-app
    expose:
      - 5000
    environment:
      VIRTUAL_HOST: thisper.levantine.io
      LETSENCRYPT_HOST: thisper.levantine.io
      LETSENCRYPT_EMAIL: letsencrypt@levantine.io
